//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyProgressManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class study_program
    {
        public int id { get; set; }
        public int no { get; set; }
        public string curriculum_id { get; set; }
        public string curriculum_name_vietnamese { get; set; }
        public string curriculum_name_english { get; set; }
        public int credits { get; set; }
        public Nullable<int> theoretical_hours { get; set; }
        public Nullable<int> practice_hours { get; set; }
        public Nullable<int> internship_hours { get; set; }
        public Nullable<int> project_hours { get; set; }
        public string compulsory_or_optional { get; set; }
        public string prerequisites { get; set; }
        public string learn_before { get; set; }
        public string editing_notes { get; set; }
        public string kind_of_knowledge { get; set; }
        public int major_id { get; set; }
        public int student_course_id { get; set; }
    
        public virtual major major { get; set; }
        public virtual student_course student_course { get; set; }
    }
}
