//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyProgressManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentcourse_curriculum
    {
        public int id { get; set; }
        public Nullable<int> student_course_id { get; set; }
        public string curriculum_id { get; set; }
    
        public virtual curriculum curriculum { get; set; }
        public virtual student_course student_course { get; set; }
    }
}
